/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
    public void testShouldBuildMethod() {
        Library classUnderTest = new Library();
        assertTrue("shouldBuild should also pass tests and return 'true'", classUnderTest.shouldBuild());
    }
}
